taxi_co2:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '/home/lburtle/work/ds3022-data-project-1/traffic.duckdb'
      schema: 'emissions'
      threads: 4
      keepalives_idle: 0
      search_path: 'emissions'